feat: reload page when clicking on create request
peanutprotocol/peanut-ui pull request #425
Opened 2024-10-07 22:30 UTC by jjramirezn

To permit easy creation of new request after creating one

2024-10-09 14:03 UTC, Hugo0 requested changes

2024-10-09 14:03 UTC, Hugo0 commented on src/components/Global/Header/index.tsx
> +            >
TODO: nice - I think this is the desired behavior. For consistency, can we have the same behaviour across all pages? So send, request, cashout.

Generally when submitting a PR we should think holistically - else we get fragmented behaviour. Even though the ticket was submitted only for request links navbar, its valid across other items, so the issue fix shouldn't just tackle the complaint, but ideally tackle whole issue holistically.  And if not, it should at least make mention of this wider issue

a very similar thing was raised in this PR from @panosfilianos: https://github.com/peanutprotocol/peanut-ui/pull/426#pullrequestreview-2356706285

2024-10-09 14:17 UTC, jjramirezn commented on src/components/Global/Header/index.tsx
> +            >
great point, implementing

2024-10-10 09:23 UTC, Hugo0 approved these changes
v nice!

2024-10-10 09:23 UTC, Hugo0 commented on src/components/Global/Header/index.tsx
> +    )
praise: nice! Way cleaner :)

2024-10-10 09:23 UTC, Hugo0 commented on src/components/Global/Header/index.tsx
> +const MenuLink = ({ route, title, isBeta = false }: { route: string; title: string; isBeta?: boolean }) => {
thought: in the future we might also want some other properties (e.g. isNew or hasNotification or similar)

2024-10-10 09:24 UTC, merged