Refactor/ternary confirm view and abstract fee explainers
peanutprotocol/peanut-ui pull request #426
Opened 2024-10-08 11:03 UTC by panosfilianos

This refers to https://github.com/peanutprotocol/peanut-ui/pull/400#discussion_r1785961248

2024-10-09 10:18 UTC, Hugo0 reviewed
I think it makes little sense to refactor this in confirm view but not in success view (where we also have these fees)

Imo: extend this PR to also cover confirm success view (and ideally move values to consts file)

wdyt @panosfilianos ?

2024-10-09 10:18 UTC, Hugo0 commented on src/components/Offramp/Confirm.view.tsx
> +    // TODO: remove hardcoding fee amounts from here and refactor to consts file
praise: good todo comment.

These should prob be pulled from `Cashout.consts.ts`

2024-10-09 10:22 UTC, panosfilianos commented on src/components/Offramp/Confirm.view.tsx
> +    // TODO: remove hardcoding fee amounts from here and refactor to consts file
fair

2024-10-09 14:28 UTC, Hugo0 requested changes
TODO: also do in success view

2024-10-15 09:32 UTC, panosfilianos commented
This branch has a file conflict w/ `develop`. This is due to renaming the consts file from `cashout.utils.ts` to `offramp.utils.ts` to retain naming convention from other parts of the codebase. Once this has passed review, I will merge `develop` in the current branch and resolve the conflict.

2025-07-03 18:22 UTC, closed without merging