[TASK-6955] feat: populate token selector with squid supported token
peanutprotocol/peanut-ui pull request #539
Opened 2024-11-20 14:44 UTC by jjramirezn

## Main focus

Instead of relaying only on our sdk list of supported chain and tokens, the token selector is now populated mainly from the supported tokens from squid, in the flows of link and request creation we also use the sdk list because we want users to be able to create those even if those wont be able to be fulfilled crosschain

## Other changes
- Cache the list of squid supported tokens for 12 hours, we don't expect this to change much
- On request pay dont show the token selector if the token doesnt support xchain
- Lazy load the images on the token selector (the lists are bigger now with all the squid tokens)

2024-11-20 23:25 UTC, jjramirezn commented
Added copy update https://www.notion.so/peanutprotocol/Bug-xchain-copy-wrong-ti-130838117579802d8cadcbdb75057e2e?pvs=4

2024-11-21 00:26 UTC, jjramirezn commented
Added fix for balance not showing https://www.notion.so/peanutprotocol/Bug-Can-get-into-bad-balance-state-on-tokenSelector-12e83811757980febfdbf6a9b62b46ba?pvs=4

2024-11-21 06:09 UTC, Hugo0 requested changes
Needs changes, review here: https://www.notion.so/peanutprotocol/Review-Bug-TokenSelector-should-not-show-non-xchain-supported-tokens-in-request-pay-and-claimlink-c-14483811757980be9e92e8fdaf8d4588

2024-11-21 06:09 UTC, Hugo0 commented on src/app/actions/squid.ts
> +import { getSquidChains, getSquidTokens } from '@squirrel-labs/peanut-sdk'
Thought: we might want to integrate across.to or a tron bridge in the future. Might want to add an abstraction layer here (ie not SquidChains, but X-chain supported chains)

2024-11-21 06:09 UTC, Hugo0 commented on src/components/Global/TokenSelector/TokenSelector.tsx
> +import { IUserBalance, IToken } from '@/interfaces'
lol? how did this happen? Automated formatting?

2024-11-22 07:34 UTC, Hugo0 approved these changes
huge ux win

2024-11-22 07:34 UTC, merged